// flow-typed signature: b7b57e0d7c1df95cee43085b130a5baa
// flow-typed version: <<STUB>>/pinyin_v2.8.3/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pinyin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pinyin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pinyin/data/dict-zi-web' {
  declare module.exports: any;
}

declare module 'pinyin/data/dict-zi' {
  declare module.exports: any;
}

declare module 'pinyin/data/phrases-dict' {
  declare module.exports: any;
}

declare module 'pinyin/lib/index' {
  declare module.exports: any;
}

declare module 'pinyin/lib/phonetic-symbol' {
  declare module.exports: any;
}

declare module 'pinyin/lib/pinyin' {
  declare module.exports: any;
}

declare module 'pinyin/lib/web-pinyin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pinyin/data/dict-zi-web.js' {
  declare module.exports: $Exports<'pinyin/data/dict-zi-web'>;
}
declare module 'pinyin/data/dict-zi.js' {
  declare module.exports: $Exports<'pinyin/data/dict-zi'>;
}
declare module 'pinyin/data/phrases-dict.js' {
  declare module.exports: $Exports<'pinyin/data/phrases-dict'>;
}
declare module 'pinyin/index' {
  declare module.exports: $Exports<'pinyin'>;
}
declare module 'pinyin/index.js' {
  declare module.exports: $Exports<'pinyin'>;
}
declare module 'pinyin/lib/index.js' {
  declare module.exports: $Exports<'pinyin/lib/index'>;
}
declare module 'pinyin/lib/phonetic-symbol.js' {
  declare module.exports: $Exports<'pinyin/lib/phonetic-symbol'>;
}
declare module 'pinyin/lib/pinyin.js' {
  declare module.exports: $Exports<'pinyin/lib/pinyin'>;
}
declare module 'pinyin/lib/web-pinyin.js' {
  declare module.exports: $Exports<'pinyin/lib/web-pinyin'>;
}
